# Generated by Django 4.2.7 on 2023-11-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_user_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_test',
        ),
    ]
